```properties
spring.config.import=optional:file:env.properties
spring.application.name=WineHub

# SERVER CONFIG
server.port=${PORT}

# DB CONFIG
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET}

# CLOUDINARY
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}

# MailGun
mailgun.apiKey=${MAILGUN_API_KEY}
mailgun.domainName=${MAILGUN_DOMAIN_NAME}
```
